aider: Changed import statement in accounting/views.py to import 'Order' class from 'accounting.order' module.
# Context:
USER:   File "/Users/drakestapleton/PycharmProjects/Django-CRM/accounting/urls.py", line 2, in <module>
    from . import views
  File "/Users/drakestapleton/PycharmProjects/Django-CRM/accounting/views.py", line 3, in <module>
    from .models import Order
ImportError: cannot import name 'Order' from 'accounting.models' (/Users/drakestapleton/PycharmProjects/Django-CRM/accounting/models.py)

ASSISTANT: The error message indicates that the Python interpreter is unable to find the 'Order' class in the 'accounting.models' module. From the summaries you provided, it seems that the 'Order' class is actually defined in the 'accounting.order' module, not 'accounting.models'.

To fix this, you need to change the import statement in the 'accounting/views.py' file. Here's how you can fix it:

```python
accounting/views.py
<<<<<<< ORIGINAL
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from .models import Order
from accounting.product import Product
from .order_generator import OrderGenerator
import datetime
=======
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from accounting.order import Order
from accounting.product import Product
from .order_generator import OrderGenerator
import datetime
>>>>>>> UPDATED
```

This change modifies the import statement to correctly import the 'Order' class from 'accounting.order'.